language:
  node_js

node_js:
  - 6
  - 5
  - 4

services:
  - mysql

env:
  global:
    - EXPREST4_MYSQL_DB:   exprest4_test
    - EXPREST4_MYSQL_USER: travis

before_script:
  - mysql -e "create database $EXPREST4_MYSQL_DB;"
